FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl

COPY . .

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

ENV PATH="/root/.local/bin:${PATH}"

RUN uv venv .venv && uv pip install -r pyproject.toml

EXPOSE 8000

ENV MCP_TRANSPORT=http

ENTRYPOINT ["uv", "run", "src/server.py"]
